---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    # Copies all files to public_html. 
    # NOTE: If your site is in a subdirectory (e.g. public_html/villatobago), 
    # update the DEPLOYPATH above.
