---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    # ── Static assets ─────────────────────────────────────────────
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    # ── Admin panel ────────────────────────────────────────────────
    - /bin/cp -R admin $DEPLOYPATH
    # ── Resident-facing PHP pages ──────────────────────────────────
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp resident_portal.php $DEPLOYPATH
    - /bin/cp resident_form.php $DEPLOYPATH
    - /bin/cp pet_form.php $DEPLOYPATH
    - /bin/cp modification_form.php $DEPLOYPATH
    - /bin/cp move_in_form.php $DEPLOYPATH
    - /bin/cp move_out_form.php $DEPLOYPATH
    - /bin/cp approve_moveout.php $DEPLOYPATH
    - /bin/cp owner_approve_tenant.php $DEPLOYPATH
    - /bin/cp amend_request.php $DEPLOYPATH
    - /bin/cp logout_resident.php $DEPLOYPATH
    - /bin/cp test_db.php $DEPLOYPATH
    - /bin/cp force_migration.php $DEPLOYPATH
    - /bin/cp test_data_dump.php $DEPLOYPATH
    - /bin/cp fix_pending_app.php $DEPLOYPATH
    # ── Config & routing ───────────────────────────────────────────
    - /bin/cp .htaccess $DEPLOYPATH
    # ── SQL Migration scripts ──────────────────────────────────────
    - /bin/cp -R database $DEPLOYPATH
    # ── Uploads directory (ensure it exists) ──────────────────────
    - mkdir -p $DEPLOYPATH/uploads
    # Trigger rebuild test
    - /bin/cp db_proxy.php $DEPLOYPATH
    - /bin/cp migrate_portal.php $DEPLOYPATH
    - /bin/cp db_proxy.php $DEPLOYPATH
