---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp test_db.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp resident_portal.php $DEPLOYPATH
    - /bin/cp amend_request.php $DEPLOYPATH
    - /bin/cp logout_resident.php $DEPLOYPATH
    - /bin/cp pet_form.php $DEPLOYPATH
    - /bin/cp modification_form.php $DEPLOYPATH
    - /bin/cp move_in_form.php $DEPLOYPATH
    - /bin/cp resident_form.php $DEPLOYPATH
    - /bin/cp owner_approve_tenant.php $DEPLOYPATH
    # Copies all files to public_html. 
    # NOTE: If your site is in a subdirectory (e.g. public_html/villatobago), 
    # update the DEPLOYPATH above.
